// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjpqgiahidqohjaaynqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcHFnaWFoaWRxb2hqYWF5bnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NzE3MjEsImV4cCI6MjA1NjU0NzcyMX0.p-AoGmfNinZCd4na78MwMUh9D4YLocg3wCl_v0a5y60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);